name: Attach Issue Link

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: '(?<=-)(.*?)(?=-)'
        body-template: |
          Fixes #%headbranch%
        body-update-action: 'suffix'
        body-uppercase-head-match: false
        lowercase-branch: false
