name: Upload dotnet package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - run: dotnet build --configuration Release ./src /p:Version=${{ steps.get_version.outputs.VERSION }}
      - name: Create the package
        run: dotnet pack --configuration Release ./src -o . /p:Version=${{ steps.get_version.outputs.VERSION }}
      - name: Publish the package to GPR
        run: dotnet nuget push ./*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
